public with sharing class Json_Opportunity{
    public String OpportunityName;
    public String OpportunityId;
    public String RevenueStartDate;
    public String OpportunityStage;
    public String ClosedDate;
    public String color;
    public String Probability;
    public Integer ContractTerm;
    public Decimal LegacyActuals;
    public Decimal ContractValue;
    public String Description;
    public List<Json_Year> FYI;
    public Json_Opportunity(){}
}